# Generated by Django 2.1.5 on 2022-06-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametime',
            name='hours_played',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
