# Generated by Django 2.1.5 on 2023-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0002_gametime_hours_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name='GameTime',
        ),
    ]
