# Generated by Django 2.1.5 on 2023-03-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0003_auto_20230323_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminMain',
            new_name='Image',
        ),
    ]
