# Generated by Django 4.1.7 on 2023-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0004_auto_20230323_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('file_extension', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('file_extension', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('file_extension', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
